# Generated by Django 5.0.6 on 2024-05-25 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(upload_to="produtos/")),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cores_disponiveis", models.CharField(max_length=255)),
                ("categoria", models.CharField(max_length=100)),
                ("quantidade_usos", models.PositiveIntegerField(default=0)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "estacao",
                    models.CharField(
                        choices=[
                            ("primavera", "Primavera"),
                            ("verao", "Verão"),
                            ("outono", "Outono"),
                            ("inverno", "Inverno"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("altura", models.DecimalField(decimal_places=2, max_digits=5)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("masculino", "Masculino"),
                            ("feminino", "Feminino"),
                            ("outro", "Prefiro não declarar"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="espelho.produto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="espelho.usuario",
                    ),
                ),
            ],
        ),
    ]
