# Generated by Django 5.0.6 on 2024-05-26 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espelho", "0003_loginespelho_remove_profile_user_remove_usuario_user"),
        ("usuario_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentacao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experimentacoes_espelho",
                to="usuario_app.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="experimentacao",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experimentacoes_espelho",
                to="espelho.produto",
            ),
        ),
        migrations.AddField(
            model_name="loginespelho",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
