# Generated by Django 4.2.13 on 2024-05-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espelho", "0004_alter_experimentacao_usuario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="KinectData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("joint_positions", models.JSONField()),
                ("height", models.FloatField()),
                ("shoulder_width", models.FloatField()),
                ("arm_length", models.FloatField()),
                ("chest_circumference", models.FloatField()),
                ("waist_circumference", models.FloatField()),
                ("hip_circumference", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="loginespelho",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Experimentacao",
        ),
        migrations.DeleteModel(
            name="LoginEspelho",
        ),
    ]
