# Generated by Django 4.2.13 on 2024-05-31 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("espelho", "0005_experimentationsession_kinectdata_userprofile_and_more"),
        (
            "lojista_app",
            "0009_variante_barcode_variante_harmonized_system_code_and_more",
        ),
        ("usuario_app", "0002_alter_experimentacao_produto_alter_reserva_produto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Produto",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="usuario_app.usuario"
            ),
        ),
        migrations.AddField(
            model_name="kinectdata",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuario_app.usuario"
            ),
        ),
        migrations.AddField(
            model_name="experimentationsession",
            name="kinect_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="espelho.kinectdata"
            ),
        ),
        migrations.AddField(
            model_name="experimentationsession",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lojista_app.produto"
            ),
        ),
        migrations.AddField(
            model_name="experimentationsession",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuario_app.usuario"
            ),
        ),
    ]
