# Generated by Django 4.2.13 on 2024-05-31 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "lojista_app",
            "0009_variante_barcode_variante_harmonized_system_code_and_more",
        ),
        ("usuario_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentacao",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experimentacoes_usuario",
                to="lojista_app.produto",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lojista_app.produto"
            ),
        ),
    ]
