# Generated by Django 5.0.6 on 2024-05-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojista_app", "0002_produto_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdutoFilho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cor", models.CharField(max_length=100)),
                ("imagem", models.ImageField(upload_to="fotos_produtos/")),
            ],
        ),
        migrations.DeleteModel(
            name="ProdutoLojista",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="cores_disponiveis",
        ),
        migrations.AddField(
            model_name="produtofilho",
            name="produto_principal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cores",
                to="lojista_app.produto",
            ),
        ),
    ]
