# Generated by Django 5.0.6 on 2024-05-27 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojista_app", "0003_produtofilho_delete_produtolojista_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="preco",
            new_name="preco_comparacao",
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="estoque",
            new_name="quantidade",
        ),
        migrations.AddField(
            model_name="produto",
            name="continuar_vendendo_sem_estoque",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="produto",
            name="localizacao",
            field=models.CharField(default="N/A", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_venda",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lojista_app.categoria"
            ),
        ),
        migrations.CreateModel(
            name="ImagemProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="produtos/")),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lojista_app.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("valor", models.CharField(max_length=100)),
                ("preco_venda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantidade", models.IntegerField()),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lojista_app.produto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProdutoFilho",
        ),
    ]
