# Generated by Django 5.0.6 on 2024-05-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lojista_app",
            "0004_categoria_rename_preco_produto_preco_comparacao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="genero",
            field=models.CharField(
                choices=[
                    ("masculino", "Masculino"),
                    ("feminino", "Feminino"),
                    ("unisex", "Unisex"),
                ],
                default=0,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
