# Generated by Django 4.2.13 on 2024-05-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojista_app", "0006_remove_produto_genero_alter_produto_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="genero",
            field=models.CharField(
                choices=[
                    ("feminino", "Feminino"),
                    ("masculino", "Masculino"),
                    ("unisex", "Unisex"),
                ],
                default=0,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
