# Generated by Django 4.2.13 on 2024-05-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojista_app", "0007_produto_genero"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="foto",
            field=models.ImageField(default=0, upload_to="categorias/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(max_length=255),
        ),
    ]
