# Generated by Django 4.2.13 on 2024-05-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojista_app", "0008_categoria_foto_alter_categoria_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="variante",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="variante",
            name="harmonized_system_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="variante",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
